global:
  resolve_timeout: 5m

route:
  receiver: 'spring-boot-webhook'

receivers:
  - name: 'spring-boot-webhook'
    webhook_configs:
      - url: 'http://api-service:8080/alert-webhook'
        send_resolved: true