global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'autonomous-api-optimizer'
    metrics_path: '/actuator/prometheus'        # <--- Important!
    static_configs:
      - targets: ['api-service:8080']
