global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-service:8080']

  - job_name: 'flask-anomaly-detection'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flask-anomaly-detection:5000']

rule_files:
  - 'alerts.yml'